# Generated by Django 5.1.6 on 2025-04-17 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('Booking Request', 'Booking Request'), ('New Booking Request', 'New Booking Request'), ('Booking Confirmation', 'Booking Confirmation'), ('Booking Rejection', 'Booking Rejection'), ('Cancellation Request', 'Cancellation Request'), ('Booking Cancellation', 'Booking Cancellation'), ('Booking Approved', 'Booking Approved'), ('Cancellation Approved', 'Cancellation Approved')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
