# Generated by Django 5.1.7 on 2025-04-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallowner',
            name='hall_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
