# Generated by Django 5.1.7 on 2025-04-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_hallowner_hall_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallowner',
            name='hall_capacity',
        ),
        migrations.RemoveField(
            model_name='hallowner',
            name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='hallowner',
            name='website',
        ),
    ]
