services:
  - type: web
    name: mandap-app
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput

    startCommand: |
      python auto_migrate.py && gunicorn marriage_hall_booking.wsgi

    plan: free
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: mandap-booking.onrender.com
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
