# Generated by Django 5.1.7 on 2025-04-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
