# Generated by Django 5.1.6 on 2025-04-20 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_cateringservice_decorationservice_photographyservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringservice',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catering_services', to='booking.hall'),
        ),
        migrations.AddField(
            model_name='decorationservice',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decoration_services', to='booking.hall'),
        ),
        migrations.AddField(
            model_name='photographyservice',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photography_services', to='booking.hall'),
        ),
        migrations.AddField(
            model_name='securityservice',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_services', to='booking.hall'),
        ),
        migrations.AddField(
            model_name='transportservice',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_services', to='booking.hall'),
        ),
    ]
