# Generated by Django 5.1.6 on 2025-04-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_cateringservice_hall_decorationservice_hall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_catering_Service',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='booking.cateringservice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_decoration_Service',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='booking.decorationservice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_photography_Service',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='booking.photographyservice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_security_Service',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='booking.securityservice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_transport_Service',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='booking.transportservice'),
        ),
    ]
