# Generated by Django 5.1.6 on 2025-06-18 12:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='customer',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('customer', 'hall')},
        ),
    ]
