# Generated by Django 5.1.6 on 2025-07-02 17:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_rename_user_wishlist_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
